default: &default
  host: localhost
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  database: icca_development

development:
  <<: *default

test:
  <<: *default
  database: icca_test

production:
  <<: *default
  database: icca_production

staging:
  <<: *default
  database: icca_staging
